[package]
name = "rom-pipeline-cli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "rom-pipeline"
path = "src/main.rs"

[dependencies]
rom-pipeline-core = { path = "../rom-pipeline-core" }
rom-pipeline-nintendo-3ds = { path = "../rom-pipeline-nintendo-3ds" }
rom-pipeline-ps2 = { path = "../rom-pipeline-ps2" }
rom-pipeline-psp = { path = "../rom-pipeline-psp" }
rom-pipeline-service = { path = "../rom-pipeline-service" }
rom-pipeline-web = { path = "../rom-pipeline-web" }
rom-pipeline-wiiu = { path = "../rom-pipeline-wiiu" }
tokio.workspace = true

[lints]
workspace = true
